# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Elijah Wahl
email: univ5824@ox.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  A space where I share recent research, thoughts and interesting ideas I have encountered in my fields of study.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elijahwahlnahmias.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  social_links:
    # twitter: jekyllrb # Keep commented out if you don't use Twitter
    github: elijahwahlnahmias
  header_pages:
    - about.md
    - portfolio.md   # <-- Example: Add a link to a 'portfolio.md' page
    - research.md    # <-- Example: Add a link to a 'research.md' page
    - contact.md     # <-- Example: Add a link to a 'contact.md' page

author:
  name: Elijah Wahl
  avatar: https://media.licdn.com/dms/image/v2/D4E03AQFp7OjPM7JRWA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1693412862712?e=1755734400&v=beta&t=bMY-kTYrm1YNQfs8P3niSCtuoIdg9SCPG1U6_NYKpkM # IMPORTANT: Double-check 'my_profile_pic.jpg' matches your exact filename!
  email: your.email@example.com # Update this to your real professional email
  github: elijahwahlnahmias

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
